### ISSUE TITLE
Webpack: Critical  Dependency Warning

### ISSUE THREAD

**Issue by karan-kang** [simonepri/project-version#2]
I get the following error when using this package with webpack.

```
WARNING in ./node_modules/project-version/index.js
9:16-75 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\Development\Test UI\Main\Project.Test\node_modules\webpack\lib\dependencies\CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Development\Test UI\Main\Project.Test\node_modules\webpack\lib\Compilation.js:694:24)
    at Compilation.finish (C:\Development\Test UI\Main\Project.Test\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (C:\Development\Test UI\Main\Project.Test\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Development\Test UI\Main\Project.Test\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Development\Test UI\Main\Project.Test\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (C:\Development\Test UI\Main\Project.Test\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by simonepri** [comment]
Can you share the piece of code where you are using this package?

**Comment by simonepri** [comment]
@Karankang007 any news about that?

**Comment by jLouzado** [comment]
```
import version from 'project-version'
.
.
.
console.log(version)
```

**Comment by simonepri** [comment]
@Karankang007 can you provide me a full example?
